### ISSUE TITLE
Sidebar in the middle of page on pageload

### ISSUE THREAD

**Issue by Globegitter** [jbutko/stickyNavbar.js#16]
If my page is scrolled down and I refresh the page, the navbar is something just randomly in the middle of the page.
![capture d ecran 2014-08-24 a 23 10 30](https://cloud.githubusercontent.com/assets/2580254/4024824/98438174-2bdb-11e4-9047-5b2b1d6c3888.png)
Here you can see the signup button, etc in the middle of the page.

**Comment by kaibakker** [comment]
Thanks @jbutko for looking at it. But its still not working? I tried some different things and changed the version number, but still the bar is hanging on reload, any other ideas?
Thanks in advance

**Comment by jbutko** [comment]
@kaibakker: Hi, really not sure why this happened on your site, it looks like it is working fine on my demo page. Anyway you can probably fix it with this workaround (I do not tested it properly but it should work IMO):
```js
var leftColVertPosition = $('.l-left').offset().top,
    windowVerticalPos = $(window).scrollTop(),
    menuBar = $('#menubar');

if (windowVerticalPos > leftColVertPosition) {
  menuBar.style.top = "0";
}

Try it, adapt it if needed and let me know.

**Comment by kaibakker** [comment]
Thank you! Works perfectly, eventual used this script...
```javascript
$(document).ready(function () {
  $('#menubar').stickyNavbar();

  var leftColVertPosition = $('.l-left').offset().top,
    windowVerticalPos = $(window).scrollTop(),
    menuBar = $('#menubar');

  if (windowVerticalPos > leftColVertPosition) {
    menuBar.css({top: "0"});
  }
});
```

**Comment by jbutko** [comment]
No problem Kai, glad I could help.
