### ISSUE TITLE
Uncaught TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by gyduxa** [jbutko/stickyNavbar.js#27]
Hello

Thank you for your plugin. I chose this because it has a github account and I like to track the plugins. 

It works very nicely but I would like to suggest an improvement, because if you're calling stickyNavbar in a page that could have only the unsticky mode (eg: resolution bigger doesnt' display scroll), there is an `Uncaught TypeError: Cannot read property 'top' of undefined`

I just added this condition
`if(typeof lastSection !== 'undefined'){`
on line 201 before `// grab bottom position of last section`
and closed it on line 255 after `} // ( windowPosition <= $selfScrollTop ) end`

**Comment by jbutko** [comment]
Hi gyduxa,

good point, I did not think of this case. I implemented your proposal and it will be included in next version bump. Thank you.
