### ISSUE TITLE
Anchors with relative URL's don't work. 

### ISSUE THREAD

**Issue by LukeNZ** [jbutko/stickyNavbar.js#30]
If I have this embedded in my navbar:

    <a href="/missions/foo/edit"><i class="fa fa-pencil"></i></a>

This won't work because it's a relative URL, and the script throws: 

    Error: Syntax error, unrecognized expression: /missions/foo/edit

The problem seems to be coming from this line in stickyNavbar.js:

    if ("http" === c.substring(0, 4) || "mailto:" === c.substring(0, 7)) return !0;

This looks like a faulty check. Can you simply not check if the URL does not contain a `#` symbol?

In the mean time, any suggestions on how to workaround this?

**Comment by jbutko** [comment]
Hi, 
just a quick fix out of my head:
replace the `if`block you mentioned with this:
```
if ("http" === c.substring(0, 4) || "mailto:" === c.substring(0, 7) || "/" === c.substring(0, 1)) return !0;
```
I did not try the code so I am not 100% it will works, but try it yourself and let me know.

**Comment by LukeNZ** [comment]
Looking good! Would you mind committing this change to the repository?

**Comment by jbutko** [comment]
Please try latest version 1.3.2 and let me know.
