### ISSUE TITLE
Add active class? 

### ISSUE THREAD

**Issue by jdmagic21** [jbutko/stickyNavbar.js#31]
Is it possible to attach a special class on elements when the sticky nav is activated?

**Comment by jbutko** [comment]
Hi Jason,
not sure what do you mean exactly but as soon as stickyNavbar plugin is activated the header gets `sticky` class which you can set through `stickyModeClass` option and at the same time every active menu item gets class `active` which can be changed via `activeClass` option.

**Comment by jbutko** [comment]
Closed for inactivity.
