### ISSUE TITLE
Could I change "nav bar position" style to vertical (not top)?

### ISSUE THREAD

**Issue by thearabbit** [jbutko/stickyNavbar.js#36]
Could I change "nav bar position" style to vertical (not top)?
```js
Body Markup    |   Navigation
..........               | .............
..........               | .............
..........               | .............
```

**Comment by jbutko** [comment]
At the moment there is no such option. Even though I did not try it you could maybe achieve it with CSS.

**Comment by thearabbit** [comment]
Thanks for your reply.
Could example?

**Comment by jbutko** [comment]
I have no example for vertical version sorry.
