### ISSUE TITLE
jQuery conflict with li a[href*=#]

### ISSUE THREAD

**Issue by enoversum** [jbutko/stickyNavbar.js#46]
Hey there, mainly stumbling over it through a jQuery version update in the latest WordPress 4.5, I realised your plugin is affected by a weak declaration including the hash character which should be escaped: 

`li a[href*=#]` should be changed to `li a[href*='#']` 

accordingly in order to work with the latest jQuery 1.x version. I added it manually in my local copy, but it would surely be nice to have it officially available through your repository :wink: .

**Comment by jbutko** [comment]
Hi, I just merged pull request #45 which fixes the issue with hash character issue. It's also in master repo.

**Comment by dancmj** [comment]
Currently line 63 still has the same problem. It must be escaped like this ` menuItemsHref = $self.find('li a[href*="#"]'),`.
