### ISSUE TITLE
Relative links do not work in Bootstrap 3 or 4

### ISSUE THREAD

**Issue by jdmagic21** [jbutko/stickyNavbar.js#47]
I am only able to add absolute links. If they are relative I get the following two errors.

Uncaught TypeError: Cannot read property 'substring' of undefined. StickyNavbar.min.js:23
jquery.stickyNavbar.min.js:23 Uncaught TypeError: Cannot read property 'focus' of null: StickyNavbar.min.js:23

**Comment by jdmagic21** [comment]
Also, this is when the links are added to the bootstrap 4 dropdown menu. They seem to work if they are top parent links.

**Comment by danielearrighi** [comment]
Add this in the `if` statement,  line 84 for a quick fix:
`|| href.substring(0, 3) === '../'`

**Comment by jbutko** [comment]
Should be fixed in https://github.com/jbutko/stickyNavbar.js/releases/tag/1.3.4
