### ISSUE TITLE
Error with relative links

### ISSUE THREAD

**Issue by danielearrighi** [jbutko/stickyNavbar.js#48]
Hello,
this line of code does not check for relative links:
`if (href.substring(0, 4) === 'http' || (href.substring(0, 5) === 'https' || href.substring(0, 7) === 'mailto:' || href.substring(0, 1) === '/')) {
          return true;
        }`
Adding a new check:
`|| href.substring(0, 3) === '../'` fixes the issue.

**Comment by jbutko** [comment]
Implemented in v.1.3.4 - https://github.com/jbutko/stickyNavbar.js/commit/e493991ef9e3ceb951f1b0e90f41ac737390c207
Thanks!
