### ISSUE TITLE
publish latest version on NPM

### ISSUE THREAD

**Issue by pvnr0082t** [jbutko/stickyNavbar.js#49]
Hi @jbutko ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team and we want to host the library.
I found that the latest version on GitHub is `v1.3.2` but on NPM is `v1.2.1`. Could you please publish the latest versions on npm to make it consistent? Thank you.

https://github.com/cdnjs/cdnjs/issues/8413

**Comment by jbutko** [comment]
Hi cdnjs team!
Npm update published. Now both github and npm are on 1.3.3
https://www.npmjs.com/package/stickyNavbar.js

Thank you!
