### ISSUE TITLE
About jquery.stickyNavbar.css

### ISSUE THREAD

**Issue by pvnr0082t** [jbutko/stickyNavbar.js#50]
Hi @jbutko ,
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs). I found that there is `jquery.stickyNavbar.css` on github repo but this file has not been published on NPM. Is it correct? 
I'd like to confirm if `jquery.stickyNavbar.css` need to be added in cdnjs. If yes, I will fetch `jquery.stickyNavbar.css` from github repo for the current versions and set npm auto-update config for the future update. I suggest to also publish `jquery.stickyNavbar.css` on NPM in the future versions because we prefer to use npm auto-updater in cdnjs.
Thank you.

https://github.com/cdnjs/cdnjs/issues/8413

**Comment by jbutko** [comment]
Hi,
it is not needed, it is a css file for demonstration page http://www.jozefbutko.com/stickynavbar/
I deleted the file from the repo.
Thank you.

**Comment by pvnr0082t** [comment]
Okay, thanks. :+1:
